import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/SideBar";
import NavBar from "@/components/common/NavBar";
import ThemeProvider from '@/providers/ThemeProvider';
import SidebarProvider from "@/providers/SidebarProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard admin",
  description: "Generated by create next app",
};

export default function Provider({
    children, // will be a page or nested layout
}: {
    children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-gray-600 `}>
        <SidebarProvider>
        <div className={`grid grid-cols-12`}>
        

          <div className='col-span-2'>
          <Sidebar />
          </div>
          <div className={`col-span-10 -ml-10 `}>
            <NavBar />
            

          <div className='pt-5 px-4'>
          { children}
          </div>
          </div>
        </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
